spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:h2:mem:testdb  # In-memory database, change to jdbc:h2:file:~/testdb if you want a file-based database
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true  # Enable H2 console for web-based database management
      path: /h2-console  # Path to access H2 console

  jpa:
    hibernate:
      ddl-auto: update  # Automatically update the schema, options: create, create-drop, update, validate
    show-sql: true  # Show SQL queries in the console

server:
  port: 8000

